### ISSUE TITLE
Extend readme

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/Simplified#4]
The readme should be extended with some more explanation of what is `Simplified.Data.Model.dll` and  what do the rings mean.

cc @warpech, @Starcounter-Jack

**Comment by per-samuelsson** [comment]
Also add in the ReadMe **Usage** section that since this commit - https://github.com/StarcounterSamples/Simplified/commit/83dcb76444cc4a4922487daf6a543d8ba9801685 - the `Simplified.Data.dll` is copied to `StarcounterBin\EditionLibraries`. I guess the idea is that it should be referenced from there in projects.

**Comment by per-samuelsson** [comment]
> Also add in the ReadMe **Usage** section [...]

(I tried doing this myself, but I didn't have sufficient rights)

**Comment by warpech** [comment]
@per-samuelsson I made some changes. Could you please review README.md again?

Now you should have access to edit it if needed.

Thanks!

If you agree it is fine, I think we can close this issue

**Comment by per-samuelsson** [comment]
> If you agree it is fine, I think we can close this issue.

Totally fine, much better than before. Thanks! I'm closing this.
